# Generated by Django 5.0.6 on 2024-06-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='favsapp.categoria'),
        ),
    ]
