# Generated by Django 5.0.6 on 2024-06-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favsapp', '0003_sites_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='photo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
